setwd("C:/Users/My/Desktop/data science/statistics/lecture 7")
install.packages("csv")
library(csv)
df<-read.csv("churnDataEss.csv")
View(df)
str(df)
summary(df)
names(df)
#check normally distribute of every variable
hist(df$accountLength)
hist(df$areaCode)
hist(df$numberVmailMessages)
hist(df$totalDayMinutes)
hist(df$totalDayCalls)
hist(df$totalDayCharge)
hist(df$totalEveMinutes)
hist(df$totalEveCalls)
hist(df$totalEveCharge)
hist(df$totalNightMinutes)
hist(df$totalNightCalls)
hist(df$totalNightCharge)
hist(df$totalIntlMinutes)
hist(df$totalIntlCalls)
hist(df$totalIntlCharge)
hist(df$numberCustomerServiceCalls)
#taking sqrt
df$totalIntlCalls<-sqrt(df$totalIntlCalls)
summary(df$totalIntlCalls)
hist(df$totalIntlCalls)
#df$numberCustomerServiceCalls<-sqrt(df$numberCustomerServiceCalls)
#summary(df$numberCustomerServiceCalls)
#hist(df$numberCustomerServiceCalls)
#to check the missing value treatment
sum(is.na(df))
names(df)
#convert categorical into dummy variable
df$internationalPlanDummy<-ifelse(df$internationalPlan==" yes",1,0)
df$voiceMailPlanDummy<-ifelse(df$voiceMailPlan==" yes",1,0)
df$churnerDummy<-ifelse(df$churner=="TRUE",1,0)
#df$internationalPlan_dummy<-ifelse(df$internationalPlan=="yes",1,0)
#df$voiceMailPlan_dummy<-ifelse(df$voiceMailPlan=="yes",1,0)
#df$churner_dummy<-ifelse(df$churner=="TRUE",1,0)
View(df)
names(df)
str(df)
summary(as.factor(df$internationalPlanDummy))
summary(as.factor(df$voiceMailPlanDummy))
summary(as.factor(df$churnerDummy))
#df$internationalPlan_dummy<-as.factor(df$internationalPlan_dummy)
#df$voiceMailPlan_dummy<-as.factor(df$voiceMailPlan_dummy)
#df$churner_dummy<-as.factor(df$churner_dummy)
df1<-df[,-c(1,2,4,5,6,21)]
View(df1)
names(df1)
#checking for outlier
bx<-boxplot(df1$accountLength)
bx$stats
quantile(df1$accountLength,seq(0,1,0.2))
#capping
df1$accountLength<-ifelse(df1$accountLength>=205,205,df1$accountLength)
bx1<-boxplot(df1$numberVmailMessages)
bx1$stats
quantile(df1$numberVmailMessages,seq(0,1,0.2))
df1$numberVmailMessages<-ifelse(df1$numberVmailMessages>=50,50,df1$numberVmailMessages)
names(df1)
bx2<-boxplot(df1$totalDayMinutes)
bx2$stats
quantile(df1$totalDayMinutes,seq(0,1,0.2))
df1$totalDayMinutes<-ifelse(df1$totalDayMinutes>=325,325,df1$totalDayMinutes)
df1$totalDayMinutes<-ifelse(df1$totalDayMinutes<=37,37,df1$totalDayMinutes)
bx2<-boxplot(df1$totalDayMinutes)
bx3<-boxplot(df1$totalDayCalls)
bx3$stats
df1$totalDayCalls<-ifelse(df1$totalDayCalls>=152,152,df1$totalDayCalls)
df1$totalDayCalls<-ifelse(df1$totalDayCalls<=47,47,df1$totalDayCalls)
bx3<-boxplot(df1$totalDayCalls)
bx4<-boxplot(df1$totalDayCharge)
bx4$stats
df1$totalDayCharge<-ifelse(df1$totalDayCharge>=55.2,55.2,df1$totalDayCharge)
df1$totalDayCharge<-ifelse(df1$totalDayCharge<=6.4,6.4,df1$totalDayCharge)
bx4<-boxplot(df1$totalDayCharge)
bx5<-boxplot(df1$totalEveMinutes)
bx5$stats
df1$totalEveMinutes<-ifelse(df1$totalEveMinutes>=337.2,337.2,df1$totalEveMinutes)
df1$totalEveMinutes<-ifelse(df1$totalEveMinutes<=64,64,df1$totalEveMinutes)
bx5<-boxplot(df1$totalEveMinutes)
bx6<-boxplot(df1$totalEveCalls)
bx6$stats
df1$totalEveCalls<-ifelse(df1$totalEveCalls>=152,152,df1$totalEveCalls)
df1$totalEveCalls<-ifelse(df1$totalEveCalls<=48,48,df1$totalEveCalls)
bx6<-boxplot(df1$totalEveCalls)
bx7<-boxplot(df1$totalEveCharge)
bx7$stats
df1$totalEveCharge<-ifelse(df1$totalEveCharge>=28.65,28.65,df1$totalEveCharge)
df1$totalEveCharge<-ifelse(df1$totalEveCharge<=5.47,5.47,df1$totalEveCharge)
bx7<-boxplot(df1$totalEveCharge)
bx8<-boxplot(df1$totalNightMinutes)
bx8$stats
df1$totalNightMinutes<-ifelse(df1$totalNightMinutes>=334.70,334.70,df1$totalNightMinutes)
df1$totalNightMinutes<-ifelse(df1$totalNightMinutes<=65.70,65.70,df1$totalNightMinutes)
bx8<-boxplot(df1$totalNightMinutes)
bx9<-boxplot(df1$totalNightCalls)
bx9$stats
quantile(df1$totalNightCalls,seq(0,1,0.2))
df1$totalNightCalls<-ifelse(df1$totalNightCalls>=152,152,df1$totalNightCalls)
df1$totalNightCalls<-ifelse(df1$totalNightCalls<=49,49,df1$totalNightCalls)
bx9<-boxplot(df1$totalNightCalls)
bx10<-boxplot(df1$totalNightCharge)
bx10$stats
quantile(df1$totalNightCharge,seq(0,1,0.2))
df1$totalNightCharge<-ifelse(df1$totalNightCharge>=15.06,15.06,df1$totalNightCharge)
df1$totalNightCharge<-ifelse(df1$totalNightCharge<=2.96,2.96,df1$totalNightCharge)
bx10<-boxplot(df1$totalNightCharge)
bx11<-boxplot(df1$totalIntlMinutes)
bx11$stats
quantile(df1$totalIntlMinutes,seq(0,1,0.2))
df1$totalIntlMinutes<-ifelse(df1$totalIntlMinutes>=17.5,17.5,df1$totalIntlMinutes)
df1$totalIntlMinutes<-ifelse(df1$totalIntlMinutes<=3.3,3.3,df1$totalIntlMinutes)
bx11<-boxplot(df1$totalIntlMinutes)
quantile(df1$totalIntlMinutes,seq(0,1,0.2))
bx12<-boxplot(df1$totalIntlCalls)
bx12$stats
quantile(df1$totalIntlCalls,seq(0,1,0.2))
df1$totalIntlCalls<-ifelse(df1$totalIntlCalls>=3.46,3.46,df1$totalIntlCalls)
df1$totalIntlCalls<-ifelse(df1$totalIntlCalls<=1.0,1.0,df1$totalIntlCalls)
bx12<-boxplot(df1$totalIntlCalls)
bx13<-boxplot(df1$totalIntlCharge)
bx13$stats
quantile(df1$totalIntlCharge,seq(0,1,0.2))
df1$totalIntlCharge<-ifelse(df1$totalIntlCharge>=4.67,4.67,df1$totalIntlCharge)
df1$totalIntlCharge<-ifelse(df1$totalIntlCharge<=0.89,0.89,df1$totalIntlCharge)
bx13<-boxplot(df1$totalIntlCharge)

#now lets do the bivariate analysis and check multicollinearity
View(df1)
install.packages("car")
library(car)
mod<-lm(churnerDummy ~ .,data=df1)
vif(mod)#vif comes exponentially here so we decide to eliminate variable one by one
summary(mod)
names(df1)
mod1<-lm(churnerDummy ~.,data=df1)
vif(mod1)
names(df1)
#now eliminate the variable which create vif value greater than 4
df2<-df1[,-c(2,5,8,11,14)]
names(df2)
mod2<-lm(churnerDummy~.,data = df2)
t=vif(mod2)
sort(t,decreasing = T)
summary(mod2)
#create test train data
set.seed(200)
t=sample(1:nrow(df2),0.7*nrow(df2))
t_train=df2[t,]
t_test=df2[-t,]
#modelbuilding
mod_glm1<-glm(churnerDummy~.,family = "binomial",data = t_train)
t_glm1=vif(mod_glm1)
sort(t_glm1,decreasing = T)
summary(mod_glm1)
#using stepmethod
stpmod=step(mod_glm1,direction = "both")
formula(stpmod)
summary(stpmod)
#now create better model which come by stepmethod
glm_mod2<-glm(churnerDummy~totalDayMinutes + totalEveMinutes + totalNightMinutes + totalIntlMinutes + totalIntlCalls + numberCustomerServiceCalls + internationalPlanDummy + voiceMailPlanDummy, data = t_train )
summary(glm_mod2)
t_train$score=predict(glm_mod2,newdata = t_train,type = "response")
head(t_train$score)
tail(t_train$score)
#lets try to analyse the confusion matrix and model accuracy
install.packages("lattice")
install.packages("ggplot2")
install.packages("caret")
install.packages("e1071")
library(lattice)
library(ggplot2)
library(caret)
library(e1071)
summary(as.factor(df2$churnerDummy))
prediction<-ifelse(t_train$score>=0.166,1,0)
View(prediction)
confusionMatrix(as.factor(prediction),as.factor(t_train$churnerDummy),positive = "1")
#lets check AUC and ROC
install.packages("InformationValue")
library(InformationValue)
plotROC(actuals = t_train$churnerDummy,predictedScores = as.numeric(fitted(glm_mod2)))
#plotROC(actuals = t_train$churnerDummy,predictedScores = t_train$score) same 
#k-s plot
ks_plot(actuals = t_train$churnerDummy,predictedScores = as.numeric(fitted(glm_mod2)))
#prediction on test data
t_test$score2=predict(glm_mod2,t_test,type="response")
View(t_test)
plotROC(actuals = t_test$churnerDummy,predictedScores = t_test$score2)
